name: calda_app
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # UI
  cupertino_icons:
  lottie:
  bot_toast:
  flutter_form_builder:
  adaptive_dialog:

  # Architecture
  state_notifier:
  flutter_hooks:
  hooks_riverpod:

  #  # Firebase
  #  firebase_core:
  #  firebase_auth:
  #  cloud_firestore:

  # Debug
  logger:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  freezed:

flutter:
  uses-material-design: true
  assets:
    - images/
    - lottie/