name: calda_app
description: The Flutter app with river_pod.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # UI
  cupertino_icons:
  lottie:
  bot_toast:
  flutter_form_builder:
  adaptive_dialog:
  flutter_speed_dial:

  # Architecture
  state_notifier:
  flutter_hooks:
  hooks_riverpod:
  json_annotation:
  get_it:
  freezed:

  # Firebase
  firebase_core:
  firebase_auth:
  cloud_firestore:

  # Debug
  logger:

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  freezed:
  json_serializable:

flutter:
  uses-material-design: true
  assets:
    - images/
    - lottie/